# app base config item - qa
server:
  abc: "ip-city.ipdb"
  debug: false #true|false
  port: 8000
  ipdbDistrict: "./ip-quxian.ipdb"
  ipdbDistrictV6: "./ipv6_china_cn.ipdb"
  ipdbCity: "./ip-city.ipdb"
weChart:
  appID: "123"
  secret: "345"
  endpointAccessToken: "https://api.weixin.qq.com/cgi-bin/token"
  endpointCode2Session: "https://api.weixin.qq.com/sns/jscode2session"
  endpointUserInfo: "https://api.weixin.qq.com/cgi-bin/user/info"
redis:
  url: redis://:Canyin131419.@114.115.153.27:8089
  poolSize: 500
  consumer:
    inverted: # 倒排表监听器。
      topic: architect-index  # 订阅的topic组
  producet:
    inverted: # 发送器监听器。
      topic: architect-db-index  # 订阅的topic组
client:
  dialContextTimeout: 30 # s 连接超时限制
  dialContextKeepalive: 30 # s keepalive探针心跳
  disableKeepalives: false # 是否复用连接
  disableCompression: true #
  maxConnsPrehost: 0 # 每个host的最大连接数量，0表示不限制
  maxidleConnsPerhost: 1000 # 每个host的连接池最大空闲连接数,默认2 0无限制
  maxidleConns: 2000 # 所有host的连接池最大连接数量，默认无穷大
  idleConnTimeout: 90 # s 连接存活时间 0 无限制
  responseHeaderTimeout: 3 #s 读取header的超时设置， 不包含读取响应体
  timeout: 0 #ms 指服务器发出的请求的时间限制  0:代表没有超时限制